name: bzflag-tjhanson
version: 2.4.18
summary: Free 3D online multi-player multi-platform tank battle game.
description: |
    BZFlag is an Open Source OpenGL multiplayer multiplatform Battle Zone
    capture the Flag game.  At its heart, the game is a 3D first person
    tank simulation where opposing teams battle for dominance.  The game
    was originally written for SGI computers running Irix, but now runs
    and is actively maintained on Windows, Linux, Mac OS X, and other
    platforms. This is an unofficial snap of the game/server.

architectures: [amd64]
confinement: strict

parts:
    bzflag:
        plugin: autotools
        source-type: tar
        source: https://github.com/BZFlag-Dev/bzflag/archive/v2.4.18.tar.gz
        build-packages:
            - g++
            - libtool
            - automake
            - autoconf
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libsdl1.2-dev
            - libcurl3-dev
            - libc-ares-dev
            - zlib1g-dev
            - libncurses-dev
            - libglew-dev
            - make
            - mesa-common-dev
        stage-packages:
            - libglu1-mesa
            - libgl1-mesa-dri
            - libgl1-mesa-glx
        #after:
        #    - desktop-glib-only
        #install: ../../../install-opengl-framework.sh
        
        override-build: |
            snapcraftctl build
            ../../../install-opengl-framework.sh
apps:
    bzflag:
        command: opengl-launch $SNAP/bin/bzflag
        plugs:
            - opengl
            - x11
            - network
            - network-bind
            - alsa
            - pulseaudio
