name: bzflag
version: 2.4.18
summary: Free 3D online multi-player multi-platform tank battle game.
description: |
    BZFlag is a 3D networked multi-player multi-platform tank battle
    game. It runs on Windows, macOS, Linux, BSD, and other platforms. It
    was one of the most popular games ever on Silicon Graphics machines
    and continues to be developed and improved to this day.

architectures: [amd64]
confinement: strict

apps:
    bzflag:
        command: desktop-launch $SNAP/bin/bzflag -directory $SNAP/share/bzflag/ -configdir $SNAP_USER_COMMON/.config/
        plugs:
            - opengl
            - x11
            - network
            - network-bind
            - alsa
            - pulseaudio
    bzfs:
        command: bzfs
        plugs:
            - network
            - network-bind

parts:
    bzflag:
        plugin: autotools
        source-type: tar
        source: https://github.com/BZFlag-Dev/bzflag/archive/v2.4.18.tar.gz
        build-packages:
            - g++
            - libtool
            - automake
            - autoconf
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - libsdl1.2-dev
            - libcurl3-dev
            - libc-ares-dev
            - zlib1g-dev
            - libncurses-dev
            - libglew-dev
            - make
            - mesa-common-dev
        stage-packages:
            - libglu1-mesa
            - libgl1-mesa-dri
            - libgl1-mesa-glx
        after:
            - desktop-glib-only
